version: 2.1
orbs:
  node: 'circleci/node@3.0.0'
jobs:
  test:
    docker:
      - image: circleci/node:13.12.0
    steps:
      - checkout
      - node/install:
          node-version: '13.12.0'
          install-npm: false
          install-yarn: true
          yarn-version: '1.22.4'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run unit tests
          command: yarn test
workflows:
  test:
    jobs:
      - test
